### ISSUE TITLE
Add sidenotes

### ISSUE THREAD

**Issue by quintik** [quintik/quant#1]
Cool sidenotes with nothing but CSS!

![image](https://user-images.githubusercontent.com/28828855/148687345-5bb0253a-acb8-44c3-8607-799ae2283bfd.png)

CSS:
```css
.sidenote {
    margin-right: -20vw;
    float: right;
    clear: right;
    width: 18vw;
    color: #393937;
    font-size: 0.8rem;
    font-style: italic;
    border-left-color: #88887a;
    border-left-style: solid;
    border-left-width: 2px;
    padding: 0 0 0 5px;
    margin-top: 0;
    margin-bottom: 0;
}
```

For smaller screens, we can have it appear in the middle of the text, with borders around it. I could try doing something like latex.vercel.app does with HTML labels and inputs but it seems like more hassle than needed.
